### ISSUE TITLE
calendar sign in not working :(

### ISSUE THREAD

**Issue by V2dha** [MLH-Fellowship/Student-Planner#2]
Whenever I try to sign using the google calendar sign in, it doesn't shows the list of calendar events for me it just shows the icon of sign out.
![capture](https://user-images.githubusercontent.com/50369708/95753121-c1392780-0cbe-11eb-883b-828e9b8a5c27.PNG)
It happened the very first time too when I accessed the qwikstart tutorial therefore I searched for another script. May be its due to the api key. What do you think?

**Comment by eamspoker** [comment]
@V2dha, did you do it by opening the file, or did you use localhost?

**Comment by V2dha** [comment]
Yups. I do believe it's due to the api key and client id that I have with me.
