### ISSUE TITLE
Decide on Name for Web app

### ISSUE THREAD

**Issue by sh-biswas** [MLH-Fellowship/Student-Planner#3]
**Summary:** 
Need to decide on a name for our web app and change our current name

**Comment by V2dha** [comment]
I am really sorry created one issue too. I have labeled it as duplicate and closed it.

**Comment by sh-biswas** [comment]
- StudyWorks
 - Virtual Academic
 - Digital Academic
 - Studyscape

These are just a few ideas from a name generator

**Comment by eamspoker** [comment]
I like Studyscape!

**Comment by sh-biswas** [comment]
Excellent! I like it too! Studyscape it is 👍
