### ISSUE TITLE
Home page design 

### ISSUE THREAD

**Issue by sh-biswas** [MLH-Fellowship/Student-Planner#6]
This is a new page design started by Vividha. We can base the rest of our color scheme and design off of this, as it is a very good starting point. Just one suggestion, I think that the features section can be a bit smaller, as it looks like it has a little too much space. But otherwise, this is just official documentation of our discussion from Discord, so feel free to comment suggestions or support here! 
![Screenshot (57)](https://user-images.githubusercontent.com/50369708/95874685-c796d480-0d8e-11eb-8919-2ff0e52b68ce.png)
![Screenshot (58)](https://user-images.githubusercontent.com/50369708/95874694-c9609800-0d8e-11eb-96e4-adb89e194008.png)
![Screenshot (59)](https://user-images.githubusercontent.com/50369708/95874702-ccf41f00-0d8e-11eb-8fb9-f54c1ff05daf.png)
![Screenshot (60)](https://user-images.githubusercontent.com/50369708/95874706-ce254c00-0d8e-11eb-8860-4c4c75771948.png)

**Comment by V2dha** [comment]
There are a few changes and things to be added as follows :- 

- If the dasboard is finally completed can you send pictures of the same I'll replace it with our web app's photos. Send me 3 screenshots.

- Send me a little content about your technical domains and tech stacks you work on to be updated in the team's section.

- Send me a link of your photo headshot or simply update your photo on your github profile to be included in the team's photos section.

Furthermore any changes to the content are welcome!

**Comment by sh-biswas** [comment]
Okay sounds good! I will send over the relevant information soon, but hopefully, we get the dashboard up soon!
